const { conectarDB } = require('../database/conexion.js')
const Nota = require('./model/Nota.js')
conectarDB();

// exports.getNotasRepository = ...

// exports.getNotaByIdRepository = ...

// exports.createNotaRepository = ...

// exports.updateNotaRepository = ...

// exports.deleteNotaRepository = ...
