const notasRepository = require('../repositories/notasRepository.js')

// exports.getNotasService = ...

// exports.getNotaByIdService = ...

// exports.createNotaService = ...

// exports.updateNotaService = ...

// exports.deleteNotaService = ...
