const notasService = require('../services/notasService.js')

// exports.getNotasController = ...

// exports.getNotaByIdController = ...

// exports.createNotaController = ...

// exports.updateNotaController = ...

// exports.deleteNotaController = ...
